window.SARA_CONFIG = {
  brandName: "saracreations0810",
  email: "saracreations0810@gmail.com",
  instagramUrl: "https://www.instagram.com/saracreations0810/",
  whatsappNumber: "919891920520"
};

window.SARA_PRODUCTS = [
  {
    id: "SC-001",
    slug: "emerald-luxury-lawn-suit",
    name: "Emerald Luxury Lawn Suit",
    brand: "Maria B",
    category: "Luxury Lawns",
    fabricType: "Un-stitched",
    price: 3499,
    stock: 12,
    featured: true,
    images: ["assets/fabric-emerald.svg", "assets/fabric-hero.svg"],
    description: "Premium lawn fabric with emerald floral work and a refined festive finish.",
    remarks: "Best for elegant day events and semi-formal gatherings.",
    tags: ["premium", "new", "floral"]
  },
  {
    id: "SC-002",
    slug: "rose-original-lawn",
    name: "Rose Original Lawn",
    brand: "Gul Ahmed",
    category: "Original Lawns",
    fabricType: "Un-stitched",
    price: 2199,
    stock: 18,
    featured: true,
    images: ["assets/fabric-rose.svg", "assets/fabric-hero.svg"],
    description: "Soft original lawn in rose and ivory tones with a delicate everyday print.",
    remarks: "Comfortable for warm weather and regular wear.",
    tags: ["lawn", "daily", "soft"]
  },
  {
    id: "SC-003",
    slug: "ivory-pure-cotton-set",
    name: "Ivory Pure Cotton Set",
    brand: "Charizma",
    category: "Pure Cottons",
    fabricType: "Un-stitched",
    price: 1899,
    stock: 9,
    featured: false,
    images: ["assets/fabric-cotton.svg", "assets/fabric-hero.svg"],
    description: "Breathable pure cotton with a clean ivory base and understated border detail.",
    remarks: "Simple, crisp, and easy to style.",
    tags: ["cotton", "comfort", "ivory"]
  },
  {
    id: "SC-004",
    slug: "burgundy-party-wear",
    name: "Burgundy Party Wear",
    brand: "Ramsha",
    category: "Party Wears",
    fabricType: "Stitched",
    price: 4999,
    stock: 4,
    featured: true,
    images: ["assets/fabric-party.svg", "assets/fabric-hero.svg"],
    description: "Stitched party wear with burgundy tones, zari-inspired detail, and a premium feel.",
    remarks: "Limited stock. Suitable for festive occasions.",
    tags: ["stitched", "party", "limited"]
  },
  {
    id: "SC-005",
    slug: "indigo-daily-wear",
    name: "Indigo Daily Wear",
    brand: "Elaf",
    category: "Daily Wears",
    fabricType: "Stitched",
    price: 1599,
    stock: 22,
    featured: false,
    images: ["assets/fabric-indigo.svg", "assets/fabric-hero.svg"],
    description: "Easy stitched daily wear with indigo block-print styling and a relaxed fit.",
    remarks: "Good for office, college, and casual outings.",
    tags: ["stitched", "daily", "indigo"]
  },
  {
    id: "SC-006",
    slug: "teal-co-ord-set",
    name: "Teal Co-ord Set",
    brand: "Nureh",
    category: "Co-ord Sets",
    fabricType: "Stitched",
    price: 2799,
    stock: 7,
    featured: true,
    images: ["assets/fabric-coord.svg", "assets/fabric-hero.svg"],
    description: "Ready-to-wear teal co-ord set with a modern geometric pattern.",
    remarks: "Pairs well with neutral sandals and minimal jewelry.",
    tags: ["co-ord", "ready", "modern"]
  },
  {
    id: "SC-007",
    slug: "mustard-two-piece",
    name: "Mustard Two Piece",
    brand: "Al-Zohaib",
    category: "Two Piece",
    fabricType: "Stitched",
    price: 2399,
    stock: 0,
    featured: false,
    images: ["assets/fabric-two-piece.svg", "assets/fabric-hero.svg"],
    description: "Mustard two piece set with contrast border styling and a bold everyday look.",
    remarks: "Currently out of stock. Keep listed for customer enquiries.",
    tags: ["two-piece", "bold", "mustard"]
  },
  {
    id: "SC-008",
    slug: "sage-luxury-lawn",
    name: "Sage Luxury Lawn",
    brand: "Nureh",
    category: "Luxury Lawns",
    fabricType: "Un-stitched",
    price: 3299,
    stock: 11,
    featured: false,
    images: ["assets/fabric-nureh.svg", "assets/fabric-zara.svg"],
    description: "Sage luxury lawn with paisley-inspired embroidery artwork and soft contrast.",
    remarks: "Recommended for refined daytime styling.",
    tags: ["luxury", "sage", "paisley"]
  },
  {
    id: "SC-009",
    slug: "ivory-occasion-wear",
    name: "Ivory Occasion Wear",
    brand: "Zara Shahjahan",
    category: "Party Wears",
    fabricType: "Un-stitched",
    price: 4599,
    stock: 5,
    featured: false,
    images: ["assets/fabric-zara.svg", "assets/fabric-party.svg"],
    description: "Ivory occasion wear fabric with warm gold detailing and an ornate finish.",
    remarks: "Ideal for family functions and festive gifting.",
    tags: ["occasion", "ivory", "gold"]
  }
];
